server:
  compression:
    enabled: true
  error:
    include-stacktrace: never
  servlet:
    context-path: /precios

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
    health:
      sensitive: false
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing.sampling.probability: 1.0

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

spring:
  application:
    name: precios
  project:
    version: '@project.version@'
    buildTimestamp: '@timestamp@'
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  jpa:
    open-in-view: false
  ## Solo entorno dev
    defer-datasource-initialization: true  
  ## Entorno Productivo
  # sql.init.mode: never
  ## Solo entorno dev
  sql.init.mode: always
  